// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ0YeCw96gCvZ1yio4q4lxHPS7LykzjA0',
    appId: '1:895907179885:web:b58be7abca689d8221be64',
    messagingSenderId: '895907179885',
    projectId: 'presensi-diengcyber',
    authDomain: 'presensi-diengcyber.firebaseapp.com',
    storageBucket: 'presensi-diengcyber.firebasestorage.app',
    measurementId: 'G-K0BLFFM025',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo2NF26WviZEfRyIldZWJ2TirgdCjDDqE',
    appId: '1:895907179885:android:c3dc948865c0b0ce21be64',
    messagingSenderId: '895907179885',
    projectId: 'presensi-diengcyber',
    storageBucket: 'presensi-diengcyber.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4VUSCu8v7y5OV4X2onbRwP2opANlrk1A',
    appId: '1:895907179885:ios:76b3afc451b1d66421be64',
    messagingSenderId: '895907179885',
    projectId: 'presensi-diengcyber',
    storageBucket: 'presensi-diengcyber.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4VUSCu8v7y5OV4X2onbRwP2opANlrk1A',
    appId: '1:895907179885:ios:76b3afc451b1d66421be64',
    messagingSenderId: '895907179885',
    projectId: 'presensi-diengcyber',
    storageBucket: 'presensi-diengcyber.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ0YeCw96gCvZ1yio4q4lxHPS7LykzjA0',
    appId: '1:895907179885:web:b777471c84f00d3b21be64',
    messagingSenderId: '895907179885',
    projectId: 'presensi-diengcyber',
    authDomain: 'presensi-diengcyber.firebaseapp.com',
    storageBucket: 'presensi-diengcyber.firebasestorage.app',
    measurementId: 'G-F97WMWK8TZ',
  );
}
